"use client";

import { useState } from "react";
import { AppShell } from "@/components/app-shell/AppShell";
import { Icon } from "@/components/ui/Icon";
import { WorkflowDiagram } from "@/components/workflow/WorkflowDiagram";
import { infographicTemplates } from "@/lib/demo-data";

export default function InfographicPage() {
  const [template, setTemplate] = useState("operating-model");
  const [variant, setVariant] = useState(1);
  const [saved, setSaved] = useState(false);
  return <AppShell><header className="topbar"><div><div className="topbar-kicker">Infographic editor</div><div className="topbar-period">Operating model / signal to action</div></div><div className="topbar-actions"><span className="status-chip"><span className="status-dot green" /> Autosaved 2 min ago</span><button className="button dark small" onClick={() => setSaved(true)}>{saved ? "Export queued" : "Export"} <Icon name="download" size={15} /></button></div></header><div className="page-wrap infographic-page"><div className="editor-toolbar"><div><div className="section-kicker">Canvas / 16:9</div><h1>Make the workflow legible</h1></div><div className="toolbar-actions"><button className="icon-button"><Icon name="refresh" size={17} /></button><button className="button ghost small">Share review <Icon name="external" size={15} /></button></div></div><div className="infographic-editor-grid"><aside className="inspector panel"><div className="inspector-block"><div className="inspector-label">Template</div>{infographicTemplates.map((item) => <button className={`template-row ${template === item.id ? "selected" : ""}`} key={item.id} onClick={() => setTemplate(item.id)}><span><strong>{item.name}</strong><small>{item.description}</small></span><span>{item.ratio}</span></button>)}</div><div className="inspector-block"><div className="inspector-label">Artwork variants</div><div className="variant-list">{[1, 2, 3].map((item) => <button className={`variant-card ${variant === item ? "selected" : ""}`} onClick={() => setVariant(item)} key={item}><div className={`variant-art v${item}`}><span>{item === 1 ? "Signal" : item === 2 ? "Flow" : "System"}</span></div><small>Variant 0{item}</small></button>)}</div></div><div className="inspector-block"><div className="inspector-label">Brand controls</div><div className="control-row"><span>Warm orange accent</span><span className="color-swatch orange-swatch" /></div><div className="control-row"><span>Logo lockup</span><span className="toggle on"><i /></span></div><div className="control-row"><span>Source footer</span><span className="toggle on"><i /></span></div></div></aside><main className="canvas-area"><div className="canvas-shell"><div className="canvas-art"><div className="canvas-topline"><span>CAPCO / AI INTELLIGENCE</span><span>WEEK 38 / 2026</span></div><div className="canvas-headline">The model is<br /><em>the message.</em></div><div className="canvas-subline">Five moves from signal to governed action.</div><div className="canvas-workflow"><WorkflowDiagram /></div><div className="canvas-footer"><span>Source: Capco AI Intelligence Workspace</span><span>01—05</span></div></div></div><div className="canvas-status"><span><i className="status-dot green" />Exact copy overlay locked</span><span>Artwork variant 0{variant} · {template === "operating-model" ? "Operating model" : "Executive snapshot"}</span><span>100%</span></div></main></div></div></AppShell>;
}
